name: Validación automática de historias en la Wiki

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]    

jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name:  Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s tests
      
